[vsti]
name = "Virtual Instrument"

[vsti.keys]
name = "Keys"

[vsti.brass]
name = "Brass"

[vsti.woodwinds]
name = "Woodwinds"

[vsti.strings]
name = "Strings"

[vsti.guitar]
name = "Guitar"

[vsti.synthesizer]
name = "Synthesizer"

[vsti.sampler]
name = "Sampler"

[vsti.drums]
name = "Drums"

[vsti.percussion]
name = "Percussion"

[vsti.ethnic]
name = "Ethnic"

[vsti.vocal]
name = "Vocal"

[fx]
name = "FX"

[fx.analysis]
name = "Analysis"

[fx.delay]
name = "Delay"

[fx.distortion]
name = "Distortion"

[fx.dynamics]
name = "Dynamics"

[fx.eq]
name = "Equalizer"

[fx.filter]
name = "Filter"

[fx.gate]
name = "Gate"

[fx.glitch]
name = "Glitch"

[fx.mastering]
name = "Mastering"

[fx.midi]
name = "MIDI"

[fx.modulation]
name = "Modulation"

[fx.pitch]
name = "Pitch Correction, Pitch Shifting, Auto-tuning"

[fx.restoration]
name = "Restoration"

[fx.reverb]
name = "Reverb"

[fx.pan]
name = "Panning, Spatial"

[fx.time]
name = "Time"

[fx.generator]
name = "Tone Generators"

[unclassified]
name = "Unclassified"

[software]
name = "Software"

[software.sampler]
name = "Sample Player"

[software.daw]
name = "Digital Audio Workstation"

[audio]
name = "Audio Files"

[vsti.ambient]
name = "Ambient"

[vsti.sound-design]
name = "Sound Design"
